mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
admin.autodiscover()
import views

urlpatterns = [
    url(r'^resizer/', include('resizer.urls')),
    url(r'^resizer1/', include('resizer1.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.default),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resizer/urls.py
from django.conf.urls import url
from resizer import views

app_name='resizer'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^upload/$', views.upload, name='upload'),
]

resizer1/urls.py
from django.conf.urls import url
from . import views

appname = 'resizer1'

urlpatterns = [
    url(r'^$', views.EArticleView.as_view(), name='article'),
]

resizer/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

class Document(models.Model):
    docfile = models.FileField(upload_to='images/')

resizer1/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

# Create your models here.

class Article(models.Model):
    
    article_title = models.CharField(max_length=200)
    article_content = models.CharField(max_length=300)
    img = models.ImageField(upload_to='resizer1/static/resizer1/images/')
    def __str__(self):
        return self.article_title
        

resizer/forms.py
from django import forms


class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file'
    )

mysite/views.py
from django.http import HttpResponse
from django.shortcuts import render_to_response
import os

def default(request):
        if request.META.get('HTTP_ACCEPT_LANGUAGE') and 'ru-RU' in request.META.get('HTTP_ACCEPT_LANGUAGE'):
                lang = 'ru'
        else:
                lang = 'en'
        ddir = os.getcwd()
        return render_to_response('default.html', {'lang': lang, 'ddir': ddir})

resizer/views.py
from django.shortcuts import render
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse

from resizer.models import Document
from resizer.forms import DocumentForm

from django.views import View
from django.shortcuts import render_to_response, get_object_or_404
from .models import *

def upload(request):
    # Handle file upload
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = Document(docfile=request.FILES['docfile'])
            newdoc.save()

            # Redirect to the document list after POST
            return HttpResponseRedirect(reverse('resizer:index'))
    else:
        form = DocumentForm()  # A empty, unbound form

    # Load documents for the list page
    # Render list page with the documents and the form
    return render(
        request,
        'resizer/upload.html',
        {'form': form}
    )

def index(request):
    wer = Document.objects.all()
    return render(request,'resizer/index.html', {'wer': wer})

resizer1/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.shortcuts import render_to_response, get_object_or_404
from .models import *
# Create your views here.

class EArticleView(View):
    template_name = 'resizer1/index.html'
    
    def get(self, request, *args, **kwargs):
        context = {}
        article = get_object_or_404(Article, pk=1)
        context['article'] = article
        return render_to_response(template_name=self.template_name, context=context)
        
    def image(request):
        images = Article.objects.all()# тут objects
        return render(request, 'resizer1/index.html',{'images':images})

mysite/templates/default.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django recipe completed</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

  </head>
  <body>
<div class="container">
<div class="jumbotron">
<p class="lead text-center">
{% if lang == "ru" %}
Django установлен.<br/>
Для запуска своего приложения необходимо:
<ul>
<li>Удалить файлы из директории {{ ddir }} и заменить их своим приложением</li>
<li>В файлах конфигурации nginx и uwsgi (/etc/nginx/conf.d/django.conf , /etc/uwsgi.d/django.ini , /etc/uwsgi/app-enabled/django.ini (в зависимости от ОС)) заменить mysite на имя Вашего приложения(его директорию)</li>
<li>Перезапустить nginx и uwsgi: service nginx restart ; service uwsgi restart</li>
</ul>
{% else %}
Django installed.</br>
For deploy Your application You need:
<li>Remove all files from {{ ddir }} and put Your application there</li>
<li>In config files (/etc/nginx/conf.d/django.conf , /etc/uwsgi.d/django.ini , /etc/uwsgi/app-enabled/django.ini (depends on OS)) replace mysite to Your application's name (dir name)</li>
<li>Restart nginx and uwsgi: service nginx restart ; service uwsgi restart</li>
{% endif %}
</p>
</div>
</div>

  </body>
</html>

mysite/templates/list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Minimal Django File Upload Example</title>
    </head>

    <body>
        <!-- List of uploaded documents -->

        <!-- Upload form. Note enctype attribute! -->
        <form action="{% url "list" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>

            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>

            <p>
                {{ form.docfile.errors }}
                {{ form.docfile }}
            </p>

            <p><input type="submit" value="Upload"/></p>
        </form>
    </body>

</html>

resizer/templates/resizer/index.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <meta charset="utf-8">
        <title>Django Upload</title>
        <link rel="stylesheet" type="text/css" href="{% static 'resizer/style.css' %}" />
    </head>
    <body>
        <!-- List of uploaded documents -->
        {% if wer %}
            <ul>
                {% for document in wer %}
                    <li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No documents.</p>
        {% endif %}
        <div>
            <!--<img src="{% static "/resizer/images/buklet-1.jpg" %}" /><img src="{% static "/resizer/images/buklet-2.jpg" %}" /><img src="{% static "/resizer/images/buklet-3.jpg" %}" /> -->
        </div>
        <a href="{% url 'resizer:upload' %}">Upload</a>
    </body>
</html>

resizer/templates/resizer/upload.html
<form action="{% url "resizer:upload" %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{{ form.non_field_errors }}</p>
    <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
    <p>{{ form.docfile.errors }} {{ form.docfile }}</p>
    <p><input type="submit" value="Upload"/></p>
</form>

<a href="{% url 'resizer:index' %}">Return to Home</a>

resizer1/templates/resizer1/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'resizer1/style.css' %}" />

{% block page %}
    <article>
        <h1>{{ article.article_title }}</h1>
        <p>{{ article.article_content }}</p>
    </article>
{% endblock %}
<img src="{% static "resizer1/images/1.jpg" %}" alt="My image"/>